# Generated by Django 4.2.4 on 2023-10-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app12', '0002_alter_registration_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='password',
        ),
    ]
