# Generated by Django 4.2.4 on 2023-10-03 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app12', '0003_remove_registration_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='paid',
        ),
    ]
